version: "3"

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./spark/jobs:/opt/bitnami/spark/jobs
    - ./spark/resources:/opt/bitnami/spark/resources
  networks:
    - spark-flow

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./airflow/Dockerfile
  env_file:
    - ./airflow/.env
  volumes:
    - ./project-mart-427214-fa427024edf2.json:/opt/airflow/project-mart-427214-fa427024edf2.json
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/output:/opt/airflow/output
    - ./spark/jobs:/opt/airflow/spark/jobs
    - ./spark/resources:/opt/airflow/spark/resources
  depends_on:
    - postgres-airflow
  networks:
    - spark-flow

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres-airflow:
    image: postgres:14.0
    container_name: postgres-airflow
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - spark-flow

  postgres-staging:
    image: postgres:14.0
    container_name: postgres-staging
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: staging_db
    volumes:
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - spark-flow

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres-staging
    networks:
      - spark-flow
    ports:
      - "5050:80"

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler
    restart: unless-stopped

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Maulana --lastname 'Ahmad Maliki' --role Admin --email maulanamaliki2007@gmail.com --password admin && airflow scheduler"

  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.1.2
    container_name: jupyter-spark
    networks:
      - spark-flow
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./project-mart-427214-fa427024edf2.json:/home/user/work/project-mart-427214-fa427024edf2.json
      - ./spark/notebooks:/home/user/work/notebooks/
      - ./spark/resources/jars:/home/user/work/jars/
    environment:
      - NOTEBOOK_DIR=/home/user/work
    command: start-notebook.sh --NotebookApp.notebook_dir=/home/user/work

networks:
  spark-flow:
